name: Build executable with GraalVM

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.1

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '19'
          components: 'native-image'

      - name : Compile Java code
        run: |
          javac -d out\production\KeyFinder src\KeyFinder\Main.java -cp "src"

      - name: Build executable
        run: |
          native-image `
          --no-fallback `
          --static `
          --report-unsupported-elements-at-runtime `
          -H:Name=KeyFinder `
          -cp out\production\KeyFinder `
          KeyFinder.Main

      - name: Upload executable artifact
        uses: actions/upload-artifact@v2
        with:
          name: KeyFinder.exe
          path: KeyFinder.exe
